name: Render and Deploy RMarkdown Website
'on': push
jobs:
  build:
    runs_on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - run: |-
          Rscript -e "deploy_path <- rmarkdown::render_site(encoding = 'UTF-8')"
          Rscript -e "Sys.setenv(DEPLOY_PATH = deploy_path)"
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@v0.2.0
        env:
          BUILD_DIR: $DEPLOY_PATH
          GH_PAT: ${{ secrets.GH_PAT }}
    container: rocker/verse:latest
